apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: frontend-destination
  namespace: project
spec:
  host: frontend.project.svc.cluster.local
  subsets:
  - name: blue
    labels:
      version: blue
  - name: green
    labels:
      version: green
