module "aks" {
  source                     = "../../../modules/aks"
  cluster_name               = var.cluster_name
  resource_group_name        = data.azurerm_resource_group.prod_rg.name
  resource_group_location    = data.azurerm_resource_group.prod_rg.location
  resource_group_id          = data.azurerm_resource_group.prod_rg.id
  dns_prefix                 = var.dns_prefix
  authorized_ip_ranges       = var.authorized_ip_ranges
  appgw_id                   = data.azurerm_application_gateway.appgw.id
  appgw_subnet_id            = data.azurerm_subnet.appgw.id
  aks_subnet_ids             = data.azurerm_subnet.aks.id
  node_count                 = var.node_count
  vm_size                    = var.vm_size
  min_count                  = var.min_count
  max_count                  = var.max_count
  service_cidr               = var.service_cidr
  dns_service_ip             = var.dns_service_ip
  log_analytics_workspace_id = data.azurerm_log_analytics_workspace.log_analytics.id
  tags                        = var.tags
}