apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: managed-db-secrets-provider-class
  namespace: managed-db
spec:
  provider: azure
  parameters:
    clientID: "cb18f226-3071-427b-9de5-0f7a97a4d86a"
    keyvaultName: "fractalkeyvault-1"
    objects: |
      array:
        - |
          objectName: db-host
          objectType: secret
        - |
          objectName: db-name
          objectType: secret
        - |
          objectName: db-password
          objectType: secret
        - |
          objectName: db-user
          objectType: secret
    tenantId: "8781e01f-34c1-4028-92df-36ec2b653313"
  secretObjects:
  - secretName: kv-secret
    type: Opaque
    data:
      - objectName: db-host
        key: db-host
      - objectName: db-name
        key: db-name
      - objectName: db-password
        key: db-password
      - objectName: db-user
        key: db-user